### ISSUE TITLE
Not working with wing ide pro 9

### ISSUE THREAD

**Issue by eino-makitalo** [wakatime/wing-wakatime#1]
Directory is either

..AppData\Roaming\Wing Pro 8\scripts

or 

C:\Program Files (x86)\Wing Pro 8\scripts

but even that I put script the upper one ... it fails

**Comment by gandarez** [comment]
Is there any log you would attach to facilitate the debugging process in our side?

**Comment by shanreta** [comment]
i am having the same issue with Wing Pro 9.1.2 and previous version 9.0 pro. After running the install.py it says restart Wing. Nowhere to install the api key, no wakatime references in tools or anywhere else. OS is Windows 11, python version 3.10, Wing is 9.1.2.1

**Comment by shanreta** [comment]
Does not appear to work with Wing 10 either. There are no mentions of Wing in the wakatime logs and it is set to debug. Notepad++ shows up fine.

**Comment by shanreta** [comment]
Hi, after some assistance from Wing developers, the solution is to run the install but put the wakatime.py file in the user/Appdata/Roaming/Wing x/scripts folder and restart. It should then work.

**Comment by alanhamlett** [comment]
Oh yes, looks like we only check for app directories up to version 9 when installing:

https://github.com/wakatime/wing-wakatime/blob/9859dd0d35eeb473ed0ce45ac22d2a2379d2ce07/install.py#L48

**Comment by alanhamlett** [comment]
Fixed with 69545ed186e19cf7067e3062933b0e2419fa56af
